[package]
name = "glacier"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
futures = "0.3.31"
glacier_macro = { path = "glacier_macro" }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
