[package]
name = "glacier"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
bytes = "1.10.0"
futures = "0.3.31"
glacier_macro = { path = "glacier_macro" }
tokio = { version = "1.43.0", features = ["full"] }
